name: Generate Template

on:
  push:
    branches: [master, v2]
  pull_request:
    branches: [master, v2]
  schedule:
    # Run every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  template:
    name: Template generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute template
        run: |
          cookiecutter . --no-input

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Run make commands
        run: |
          cd project_name
          make requirements
          make dev_requirements
          make clean
          make help

      - name: Build documentation
        run: |
          cd project_name
          make build_documentation